/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mamgment.VIEW;

public class UpdateCourse extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCourse
     */
    public UpdateCourse() {
        setTitle("Courses");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUpdateALL_Button = new javax.swing.JButton();
        jUpdateName_Button = new javax.swing.JButton();
        jUpdateDate_Button = new javax.swing.JButton();
        jUpdateNumOfStudents_Button = new javax.swing.JButton();
        jUpdateNumOfLect_Button = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUpdateALL_Button.setText("Update All");
        jUpdateALL_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateALL_ButtonActionPerformed(evt);
            }
        });

        jUpdateName_Button.setText("Update name");
        jUpdateName_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateName_ButtonActionPerformed(evt);
            }
        });

        jUpdateDate_Button.setText("Update date");
        jUpdateDate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateDate_ButtonActionPerformed(evt);
            }
        });

        jUpdateNumOfStudents_Button.setText("Update number of students");
        jUpdateNumOfStudents_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateNumOfStudents_ButtonActionPerformed(evt);
            }
        });

        jUpdateNumOfLect_Button.setText("Update number of lectures");
        jUpdateNumOfLect_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateNumOfLect_ButtonActionPerformed(evt);
            }
        });

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUpdateALL_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateDate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateNumOfLect_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUpdateName_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateNumOfStudents_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateALL_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateName_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateDate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdateNumOfStudents_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateNumOfLect_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateALL_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateALL_ButtonActionPerformed
        // TODO add your handling code here:
        new UpdateAllCourse().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jUpdateALL_ButtonActionPerformed

    private void jUpdateName_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateName_ButtonActionPerformed
        // TODO add your handling code here:
        new UpdateCourseName().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jUpdateName_ButtonActionPerformed

    private void jUpdateDate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateDate_ButtonActionPerformed
        // TODO add your handling code here:
        new UpdateCourseDate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jUpdateDate_ButtonActionPerformed

    private void jUpdateNumOfStudents_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateNumOfStudents_ButtonActionPerformed
        // TODO add your handling code here:
        new UpdateCourseNumberOfStudents().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jUpdateNumOfStudents_ButtonActionPerformed

    private void jUpdateNumOfLect_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateNumOfLect_ButtonActionPerformed
        // TODO add your handling code here:
        new UpdateCourseNumberOfLectures().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jUpdateNumOfLect_ButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Courses().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jUpdateALL_Button;
    private javax.swing.JButton jUpdateDate_Button;
    private javax.swing.JButton jUpdateName_Button;
    private javax.swing.JButton jUpdateNumOfLect_Button;
    private javax.swing.JButton jUpdateNumOfStudents_Button;
    // End of variables declaration//GEN-END:variables
}
